### ISSUE TITLE
Get a full blue screen when launching JNLP

### ISSUE THREAD

**Issue by mrif0393** [nokia/jspy#18]
@mihaiparvu I can launch the JNLP file and inspect the elements.But when I re indexing getting a full blue screen.Appreciate your help. Below is a the login screen,
<img width="993" alt="screen shot 2018-11-02 at 12 23 31 pm" src="https://user-images.githubusercontent.com/32276436/47898420-cdde5f80-de9b-11e8-94ec-bbcd3e3f670e.png">

**Comment by BeniGroza** [comment]
Hi @mrif0393
 
Can you add your terminal screen? The message from client might provide some info about why this is not working.

BR,
Beni

**Comment by mrif0393** [comment]
@BeniGroza  Thanks for the response. This is the log ,I do not see any exceptions.
[log.txt](https://github.com/nokia/jspy/files/2557143/log.txt)

**Comment by mrif0393** [comment]
I was able to fix this,By removing the set background color when mouse hover.

**Comment by BeniGroza** [comment]
Hi again

I've tried to reproduce the blue screen error but didn't succeed. 
I'll close the issue but it can be re-opened if additional information are given.
